sudo: required
services:
  - docker

before_install:
  - docker build -t szt0172688/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true szt0172688/multi-docker npm run test -- --coverage


after_success:
  - docker build -t szt0172688/multi-client ./client
  - docker build -t szt0172688/multi-nginx  ./nginx
  - docker build -t szt0172688/multi-server ./server
  - docker build -t szt0172688/multi-worker ./worker

  # log in to docker CLI
  - eco "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those image and push to docker hub
  - docker push szt0172688/multi-client
  - docker push szt0172688/multi-nginx
  - docker push szt0172688/multi-server
  - docker push szt0172688/multi-worker


